# Generated by Django 3.1.1 on 2020-09-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0003_donation_is_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(null=True),
        ),
    ]
