# Generated by Django 3.1.1 on 2020-09-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0004_auto_20200929_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
