# Generated by Django 3.1.1 on 2020-10-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0005_auto_20200929_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_taken',
        ),
    ]
