# Generated by Django 3.1.1 on 2020-10-08 12:03

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0006_remove_donation_is_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=15),
        ),
    ]
