# Generated by Django 3.1.1 on 2020-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0008_auto_20201008_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
